// Auto-generated by scripts/buildDashboard311.js — do not edit manually.
// Re-run: node scripts/buildDashboard311.js
import rawData from './dashboard311.json'

export type IssueTypeMetrics = {
  resolvedPct:  number
  avgTimeLabel: string
}

export type RealIssueType = {
  id:                  string
  name:                string
  icon:                string
  iconBg:              string
  coordinateEstimated: boolean
  sparkline:           number[]
  monthlySparkline:    number[]
  peakMonth:           string | null
  firstYear:           number
  countByPeriod:       { month: number; year: number; all: number }
  month:               IssueTypeMetrics
  year:                IssueTypeMetrics
  all:                 IssueTypeMetrics
}

export type SummaryCardData = {
  resolutionRate:      number
  resolutionRateDelta: number
  avgFixTimeLabel:     string
  avgFixTimeDays:      number | null
  avgFixTimeDelta:     number | null
}

export type TrendItem = {
  name: string
  pct:  number
}

export type ChronicSpot = {
  count:            number
  location:         string
  issueType:        string
  icon:             string
  iconBg:           string
  since:            number
  reopenCount:      number
  maxConsecYears:   number
  returnMedianDays: number | null
  timelineEvents:   { date: string; eventType: 'resolved' | 'reported' }[]
  recentActivity:   { date: string; status: string; resolutionDays: number | null }[]
}

type RealDistrictData = {
  sparklineRate:    number[]
  sparklineOpen:    number[]
  sparklineAvgDays: (number | null)[]
  monthlyRate:      number[]
  monthlyAvgDays:   (number | null)[]
  volumeByYear:     number[]
  totalReports:     number
  trendsVsMonth:    TrendItem[]
  trendsVsYear:     TrendItem[]
  issueTypes:       RealIssueType[]
  byPeriod: {
    month: { summary: SummaryCardData }
    year:  { summary: SummaryCardData }
    all:   { summary: SummaryCardData }
  }
  chronicSpots: ChronicSpot[]
}

type Dashboard311 = {
  meta:      { generatedAt: string; currentMonth: string; currentYear: number }
  citywide:  { resolutionByYear: number[]; volumeByYear: number[] }
  districts: Record<string, RealDistrictData>
}

export const dashboard311 = rawData as unknown as Dashboard311
