// Auto-generated by scripts/buildDashboard311v2.js — do not edit manually.
// Re-run: node scripts/buildDashboard311v2.js
import rawData from './dashboard311v2.json'

export type CategoryComparisonItem = {
  type:           string
  fixTimeHours:   number | null
  resolutionRate: number
  volume:         number
}

export type TopIssueItem = {
  type:  string
  count: number
  icon:  string
}

export type TrendPoint = {
  period: string
  count:  number
}

export type TrendLines = {
  [typeName: string]: {
    monthly: TrendPoint[]
    yearly:  TrendPoint[]
  }
}

export type DistrictMetrics = {
  resolutionRate:  number
  avgFixTimeHours: number | null
  totalReports:    number
}

export type ChronicSpotV2 = {
  count:            number
  location:         string
  issueType:        string
  icon:             string
  iconBg:           string
  since:            number
  reopenCount:      number
  incidentCount:    number
  maxConsecYears:   number
  returnMedianDays: number | null
  timelineEvents:   { date: string; eventType: 'resolved' | 'reported' }[]
  recentActivity:   { date: string; status: string; resolutionDays: number | null }[]
}

type DistrictV2Data = {
  categoryComparison: {
    month: CategoryComparisonItem[]
    year:  CategoryComparisonItem[]
  }
  topIssues:       TopIssueItem[]
  trendLines:      TrendLines
  recurringIssues: ChronicSpotV2[]
}

type DashboardV2 = {
  meta: {
    generatedAt:      string
    currentMonth:     string
    currentYear:      number
    isPartialMonth:   boolean
    priorMonth:       string
    ytdMonths:        number[]
    avgMonthlyVolume: number
  }
  districts: Record<string, DistrictV2Data>
  districtComparison: {
    month:       Record<string, DistrictMetrics>
    year:        Record<string, DistrictMetrics>
    cityAverage: { month: DistrictMetrics; year: DistrictMetrics }
  }
}

export const dashboardV2 = rawData as unknown as DashboardV2

export const districtNames: Record<string, string> = {
  "1":  "W. San Jose / Meridian",
  "2":  "Evergreen / E. Foothills",
  "3":  "Downtown / Little Portugal",
  "4":  "Berryessa / N. Valley",
  "5":  "Alum Rock / East Side",
  "6":  "Willow Glen / Rose Garden",
  "7":  "East San Jose / Tully",
  "8":  "Silver Creek / Evergreen",
  "9":  "Blossom Hill / Edenvale",
  "10": "Almaden Valley / S. San Jose",
}
